### ISSUE TITLE
屏幕亮度无法控制

### ISSUE THREAD

**Issue by FrankXie168** [hoanX/xps13-9360-i7-7560u#10]
hi，我的设备是xps13 9360 i5 7200u,3K屏幕（分辨率相同），其他的声卡、显卡、蓝牙WIFI睡眠都OK，唯独屏幕亮度无法控制，遗留的问题：
1、屏幕亮度控制是哪一个文件或多个文件配合生效？
2、是否硬件相同的电脑hotpath都通用呢？
感谢大家讨论。

**Comment by FrankXie168** [comment]
> hi，我的设备是xps13 9360 i5 7200u,3K屏幕（分辨率相同），其他的声卡、显卡、蓝牙WIFI睡眠都OK，唯独屏幕亮度无法控制，遗留的问题：
> 1、屏幕亮度控制是哪一个文件或多个文件配合生效？
> 2、是否硬件相同的电脑hotpath都通用呢？
> 感谢大家讨论。

以上问题已解决，感谢发布clover文件。

**Comment by hoanX** [comment]
hotpatch在xps9360上都一样的，一般升级后遇到快捷键无法控制亮度，重建缓存就好了
