### ISSUE TITLE
simbios 修改为14,1摄像头不能用，usb口也不通电

### ISSUE THREAD

**Issue by FDUpiggy** [hoanX/xps13-9360-i7-7560u#11]
您好我一直以来使用您的efi，一切都很好。今天尝试将simbios修改为14,1，摄像头不工作，usb口也完全不通电。我的配置和您完全一样，是7代u，是不是8代u才能改为14,1 ？

修改回13,1 后一切正常。

**Comment by hoanX** [comment]
usbports.kext与smbios绑定，尝试更新最新版本，更改为老的驱动方式

**Comment by FDUpiggy** [comment]
是这个原因啊，感谢分享！
