### ISSUE TITLE
新版usb驱动问题

### ISSUE THREAD

**Issue by zou2699** [hoanX/xps13-9360-i7-7560u#12]
最新的usb驱动无法连接移动硬盘，连接无反应，使用之前的USB-Inject-All就可以连接。

**Comment by hoanX** [comment]
尝试最新版本，已还原老的驱动方式

**Comment by zou2699** [comment]
好的，我已经使用usbInjectAll了。我在电源里取消勾选唤醒以供wifi网络访问，可以避免唤醒后蓝牙丢失，不知道对你有没有用
