### ISSUE TITLE
IMessage终于登上去了，您的config.plist有个小问题

### ISSUE THREAD

**Issue by technicas** [hoanX/xps13-9360-i7-7560u#17]
<key>MLB</key>
<string>
C07QJ01TG1J1
C07539200LCFYRFA5
</string>

您的MLB这里是两行，也许是删除的时候没有删干净，然后在Clover Configurator中看是空的，删除MLB后，就可以登录了。

**Comment by hoanX** [comment]
好像是的，Clover Configurator看起来空的，我不用message这些所有没感觉到
