### ISSUE TITLE
你的电脑因为出现问题而重新启动

### ISSUE THREAD

**Issue by zhoulizhengithub** [hoanX/xps13-9360-i7-7560u#5]
Anonymous UUID:       ECCE56AB-DF8C-B7D4-9688-EC38FDC3A5CE

Tue Sep 11 13:34:29 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f8e1a9305): assertmsg@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-10.34.27/Common/IONDRV/Intel/KBL/AppleIntelFramebuffer/AppleIntelController.cpp:27617
Backtrace (CPU 2), Frame : Return Address
0xffffff81fabe3a80 : 0xffffff8009e6d166
0xffffff81fabe3ad0 : 0xffffff8009f95824
0xffffff81fabe3b10 : 0xffffff8009f87b10
0xffffff81fabe3b90 : 0xffffff8009e1f180
0xffffff81fabe3bb0 : 0xffffff8009e6cbdc
0xffffff81fabe3ce0 : 0xffffff8009e6c99c
0xffffff81fabe3d40 : 0xffffff7f8e1a9305
0xffffff81fabe3db0 : 0xffffff7f8e1a5d32
0xffffff81fabe3e40 : 0xffffff800a47327d
0xffffff81fabe3e80 : 0xffffff800a472fc1
0xffffff81fabe3f00 : 0xffffff800a4724e7
0xffffff81fabe3f50 : 0xffffff800a474146
0xffffff81fabe3fa0 : 0xffffff8009e1e4f7
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelKBLGraphicsFramebuffer(10.3.4)[7EAAC876-407A-3AAF-8292-CE047EF6B232]@0xffffff7f8e17d000->0xffffff7f8e37dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1057F053-73DE-33E4-B5BE-09DA28715DB4]@0xffffff7f8a6e6000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f8a6dd000
            dependency: com.apple.iokit.IOAcceleratorFamily2(378.18.1)[BAA0383C-9650-3934-B04A-69008F757A2C]@0xffffff7f8e0dd000
            dependency: com.apple.iokit.IOReportFamily(31)[D2F2FBDF-4EE4-38BA-99F5-B699F886F413]@0xffffff7f8a6d6000
            dependency: com.apple.AppleGraphicsDeviceControl(3.18.52)[FC5E4CD4-7730-3A55-9CC5-338A64F50E42]@0xffffff7f8e174000
            dependency: com.apple.iokit.IOGraphicsFamily(519.19)[0B3857C5-9040-3A0C-BFB4-C45E56DB01C6]@0xffffff7f8e037000

BSD process name corresponding to current thread: kernel_task
Boot args: -v darkwake=0 abm_firstpolldelay=16000 root-dmg=file:///Install%20macOS%20High%20Sierra.app/Contents/SharedSupport/BaseSystem.dmg

Mac OS version:
17F77

Kernel version:
Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
Kernel UUID: CC1699EE-71B5-3AF1-AAA3-6DBD16222B92
Kernel slide:     0x0000000009c00000
Kernel text base: 0xffffff8009e00000
__HIB  text base: 0xffffff8009d00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)

System uptime in nanoseconds: 64152141755
last loaded kext at 63459343268: com.apple.driver.AppleIntelKBLGraphicsFramebuffer	10.3.4 (addr 0xffffff7f8e17d000, size 2101248)
loaded kexts:
com.no-one.BrcmPatchRAM2	2.2.10
com.no-one.BrcmFirmwareStore	2.2.10
org.rehabman.voodoo.driver.PS2Keyboard	1.8.34
org.rehabman.voodoo.driver.PS2Mouse	1.8.34
org.hwsensors.driver.LPCSensors	1787
org.rehabman.driver.FakePCIID	1.3.12
com.alexandred.VoodooI2C	2.0.3
org.hwsensors.driver.ACPISensors	1787
org.coolstar.VoodooGPIO	1.1
org.rehabman.voodoo.driver.PS2Controller	1.8.34
org.hwsensors.driver.CPUSensors	1787
as.vit9696.WhateverGreen	1.2.0
org.rehabman.driver.AppleSmartBatteryManager	1.81.4
as.lvs1974.AirportBrcmFixup	1.1.3
as.vit9696.AppleALC	1.2.8
org.tw.CodecCommander	2.5.2
org.netkas.driver.FakeSMC	1787
as.vit9696.Lilu	1.2.5
com.rehabman.driver.USBInjectAll	0.6.6
com.alexandred.VoodooI2CServices	1
com.apple.driver.AppleIntelKBLGraphicsFramebuffer	10.3.4
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleMCCSControl	1.5.5
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleBacklight	170.12.6
com.apple.filesystems.ntfs	3.13
com.apple.nke.webcontentfilter	5
com.apple.driver.DiskImages.ReadWriteDiskImage	480.60.1
com.apple.driver.DiskImages.SparseDiskImage	480.60.1
com.apple.driver.DiskImages.UDIFDiskImage	480.60.1
com.apple.driver.DiskImages.HTTPBackingStore	480.60.1
com.apple.driver.DiskImages.FileBackingStore	480.60.1
com.apple.driver.DiskImages.RAMBackingStore	480.60.1
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.apfs	748.51.0
com.apple.filesystems.hfs.kext	407.50.6
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.driver.AirPort.Brcm4360	1240.19.1a3
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.AppleGraphicsDeviceControl	3.18.52
com.apple.iokit.IOAcceleratorFamily2	378.18.1
com.apple.iokit.IOSurface	211.12
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	519.19
com.apple.iokit.IOGraphicsFamily	519.19
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.DiskImages.KernelBacked	480.60.1
com.apple.driver.AppleThunderboltNHI	4.7.2
com.apple.iokit.IOThunderboltFamily	6.7.8
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleXsanScheme	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.60.2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.50.3
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.iokit.IOTimeSyncFamily	680.15
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.DiskImages	480.60.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOBluetoothFamily	6.0.6f2
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro13,1, BootROM MBP131.0223.B00, 2 processors, Intel Core i7, 2.4 GHz, 16 GB, SMC 2.36f97
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x19), Broadcom BCM43xx 1.0 (7.21.190.18.1a3)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Integrated_Webcam_HD
USB Device: Touchscreen
USB Device: BCM20702A0
USB Device: USB Optical Mouse
Thunderbolt Bus:

**Comment by hoanX** [comment]
看起来不像使用我最新的配置文件，我仿冒了SKL的ID，你的还是显示KBL，还有Boot args也不是最新，尝试使用最新配置文件，最好重建缓存一次

**Comment by zhoulizhengithub** [comment]
> 看起来不像使用我最新的配置文件，我仿冒了SKL的ID，你的还是显示KBL，还有Boot args也不是最新，尝试使用最新配置文件，最好重建缓存一次

我是直接打包下载的你的ＥＦＩ的哦怎么会不一样呢其怪

**Comment by zhoulizhengithub** [comment]
我用的是黑果小兵的　镜像，但我没有用他的ＥＦＩ，是不是做的镜像有改过呢，可否可以下大神的镜像下载地址
