### ISSUE TITLE
升级ＢＩＯＳＳ到2。9。0后无法安装，降回去也不行，

### ISSUE THREAD

**Issue by zhoulizhengithub** [hoanX/xps13-9360-i7-7560u#7]

**Comment by zhoulizhengithub** [comment]
> 升级后看看能不能修改DVMT，我还没升级

修改DVMT正常有值，但是就是安装到最后两分钟的时候自动重启，安装失败。。之前是不会的，我升级2.9.0后也重新正常成功安装过一次，后面是网上查总是不正常关机问题，重装，这时发现装不进去了，用27号的更新也无法安装，也一样不知道我电脑BIOSS哪里有错误还是怎样。

**Comment by hi-KK** [comment]
> > 升级后看看能不能修改DVMT，我还没升级
> 
> 修改DVMT正常有值，但是就是安装到最后两分钟的时候自动重启，安装失败。。之前是不会的，我升级2.9.0后也重新正常成功安装过一次，后面是网上查总是不正常关机问题，重装，这时发现装不进去了，用27号的更新也无法安装，也一样不知道我电脑BIOSS哪里有错误还是怎样。

我也是啊，升级的2.9版本bios然后关了安全启动和修改AHCI，然后用黑果小兵的镜像安装到最后两分钟重启安装失败，这下
win10也不能正常使用了，要重装系统。。。。

**Comment by zhoulizhengithub** [comment]
> > > 升级后看看能不能修改DVMT，我还没升级
> > 
> > 
> > 修改DVMT正常有值，但是就是安装到最后两分钟的时候自动重启，安装失败..之前是不会的，我升级2.9.0后也重新正常成功安装过一次，后面是网上查总是不正常关机问题，重装，这时发现装不进去了，用27号的更新也无法安装，也一样不知道我电脑的BIOS哪里有错误还是怎样。
> 
> 我也是啊，升级的2.9版本的BIOS然后关了安全启动和修改AHCI，然后用黑果小兵的镜像安装到最后两分钟重启安装失败，这下
> win10也不能正常使用了，要重装系统？ 。
win10 引导修复一下就可也了，win10是正常的

**Comment by hoanX** [comment]
我之前升2.8.1内存频率识别都错了，2133变成了1866，然后mac下还容易卡死自动重启，降回去正常，一直没敢升级，win进不去，PE下修复下就好了

**Comment by zhoulizhengithub** [comment]
> 我之前升2.8.1内存频率识别都错了，2133变成了1866年，然后MAC下还容易卡死自动重启，降回去正常，一直没敢升级，赢得进不去，PE下修复下就好了

主要是我现在降回去也是装到还有2分钟就自动重启，是否可以加一下你的QQ我把重启的的视频发你看看呢？

**Comment by hoanX** [comment]
QQ群633956297

**Comment by zhoulizhengithub** [comment]
这个qq群找不到，号码写错了……

**Comment by zhoulizhengithub** [comment]
> 633956297

这个QQ群找不到，号码写错了......

**Comment by hoanX** [comment]
可以了，之前搜群号被关了
