### ISSUE TITLE
iMessage、facetime登录不上去。

### ISSUE THREAD

**Issue by technicas** [hoanX/xps13-9360-i7-7560u#9]
您好，提交一个问题。
10月13号更新后，imessage、facetime都登录不上去了。用的我之前的三码，以前的版本都是可以。

**Comment by hoanX** [comment]
我9月份的时候修改过smbios，改成了mbp13,1，原来是14,1,不知道这个有没有影响，因为仿冒了显卡，这个smbios更合适，你可以试试改回去，我自己不用这些

**Comment by technicas** [comment]
感谢。应该不是这个原因，之前也一直在用你的EFI，就是昨天的用完了，不行了。我查了下，wifi也是build in，除了内建，还有哪些条件是必须的呢？

**Comment by hoanX** [comment]
可能是MLB没有删除干净导致，已经更新
